# Generated by Django 4.1.4 on 2022-12-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_api'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='apps',
            new_name='android',
        ),
        migrations.AddField(
            model_name='api',
            name='document',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='ios',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='web',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
