# Generated by Django 4.1.4 on 2022-12-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_webmain_center_webmain_left_webmain_rigth'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmain',
            name='first_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webmain',
            name='first_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
