# Generated by Django 4.1.4 on 2022-12-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_text',
            name='text2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_text',
            name='title2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
