# Generated by Django 4.1.4 on 2022-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_about_us_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='text2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
