# Generated by Django 4.1.4 on 2022-12-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='width',
            name='email',
        ),
        migrations.AddField(
            model_name='width',
            name='titile1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
