# Generated by Django 4.1.4 on 2022-12-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_width_email_width_titile1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='width',
            old_name='titile1',
            new_name='titile5',
        ),
    ]
