# Generated by Django 4.1.4 on 2022-12-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_online_img_facebook_online_img_tweeter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='online',
        ),
    ]
