# Generated by Django 4.1.4 on 2022-12-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_blog_site_delete_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_site',
            name='mini_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
